### ISSUE TITLE
Export of draw layer

### ISSUE THREAD

**Issue by jokd** [origo-map/draw-plugin#13]
It would be useful to be able to export as well as import draw layers.

**Comment by johnnyblasta** [comment]
It would be useful to be able to get a GeoJSON for the drawn objects just by clicking a button. It's possible to get the drawn features as GeoJSON with the share link function and Origoserver but some what cumbersome.

**Comment by jokd** [comment]
Agree, and with the features styling attached it would be close to awesome.

**Comment by jokd** [comment]
Solved in the draw control
