### ISSUE TITLE
Conflict with editor control

### ISSUE THREAD

**Issue by Owemyr** [origo-map/draw-plugin#23]
- With latest Origo-master (2021-01-26), button to activate/deactivate editor not working when draw-plugin is initiated.
![im.age](https://user-images.githubusercontent.com/47249045/105812941-54b51080-5faf-11eb-963c-2acf2b3f5b68.png)

- Draw with draw-plugin result in error when editor is allready activated (button state of editor change to deactivated but then result in error)
![image](https://user-images.githubusercontent.com/47249045/105813561-516e5480-5fb0-11eb-9bd8-474caeebf12c.png)

**Comment by jokd** [comment]
Looking into this I see theres a conflict between the draw plugin and the editor. They are related and listens to the same events. 
Rewriting the drawplugin without jQuery is probably the way to go.
