### ISSUE TITLE
Plugin not working, MenuItem

### ISSUE THREAD

**Issue by Owemyr** [origo-map/draw-plugin#47]
Draw-plugin not working with latest origo-master.
Not sure if plugin or origo-master should be bug-fixed, seems related to "MenuItem"
![image](https://user-images.githubusercontent.com/47249045/133736922-6b64a40b-8b18-4d71-ab91-5dcf7d2d8ebd.png)

**Comment by jokd** [comment]
Are you using latest draw-plugin as well? Merged a million package updates for the draw plugin the other day hence the question.

**Comment by Owemyr** [comment]
Yes, using latest from draw-plugin, merged the million packages today :)
I also tried with a clean build from origo-master and the draw-plugin.

**Comment by jokd** [comment]
Seems Origo dispatches the load event before all controls are loaded and that's the reason why it can't find mapMenu. I'll try fix it.

**Comment by jokd** [comment]
Fixed with https://github.com/origo-map/origo/pull/1346
