### ISSUE TITLE
Case-insensitive import refs in drawhandler.js prevent building on case sensitive systems

### ISSUE THREAD

**Issue by Grammostola** [origo-map/draw-plugin#5]
import Select from 'ol/interaction/select';
import Modify from 'ol/interaction/modify';
import Draw from 'ol/interaction/draw';
import DoubleClickZoom from 'ol/interaction/doubleclickzoom';
import GeoJSON from 'ol/format/geojson';

wishes to become

import Select from 'ol/interaction/Select';
import Modify from 'ol/interaction/Modify';
import Draw from 'ol/interaction/Draw';
import DoubleClickZoom from 'ol/interaction/DoubleClickZoom';
import GeoJSON from 'ol/format/GeoJSON';

Thanks

**Comment by tonnyandersson** [comment]
@Grammostola Will fix.

**Comment by tonnyandersson** [comment]
Fixed with #7.
