### ISSUE TITLE
Layers activated randomly when draw tools selected

### ISSUE THREAD

**Issue by Grammostola** [origo-map/draw-plugin#6]
-Download the latest Origo client (master) and build it
-Download this draw-plugin and build it and put it in a plugins/ folder under the origo client folder as per the instructions
-Configure (-> origo-client-folder/index.html) as per instructions in this repository's readme in order to load the draw plugin
-Add around ten layers, wms or wfs doesn't appear to matter, to the index.json
-Npm run start the origo client
-Activate the draw toolbar and open the map layer list/legend
-Click the various draw tools once each to activate them and watch the map/ f12-> network

Expected result: no getmap / getfeature fetches
Result: seemingly random getmaps / getfeatures. Even if they show up in the map they aren't activated in the legend, if you click to activate them you get a second identical layer drawn on top of the first

Reproduced on two different machines.

**Comment by tonnyandersson** [comment]
@Grammostola Known bug. We have a quick fix kinda ready for implementation. I'll try to get it done during next week.
