### ISSUE TITLE
Make it possible to config style

### ISSUE THREAD

**Issue by johnnyblasta** [origo-map/draw-plugin#9]
The drawStyle is integrated into the code without any possibility to config.

It would be nice to be able to supply a custom drawStyle or at least be able to set color and width.

**Comment by jokd** [comment]
@johnnyblasta is this solved with #19?

**Comment by johnnyblasta** [comment]
> @johnnyblasta is this solved with #19?

@jokd yes and then some!

**Comment by jokd** [comment]
Closed with #19
